# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/stuart/Source/redist_project/ui/DlgAddBEF.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dlgAddBEF(object):
    def setupUi(self, dlgAddBEF):
        dlgAddBEF.setObjectName("dlgAddBEF")
        dlgAddBEF.resize(400, 300)
        self.gridLayout = QtWidgets.QGridLayout(dlgAddBEF)
        self.gridLayout.setObjectName("gridLayout")
        self.lblBEFFile = QtWidgets.QLabel(dlgAddBEF)
        self.lblBEFFile.setObjectName("lblBEFFile")
        self.gridLayout.addWidget(self.lblBEFFile, 0, 0, 1, 1)
        self.fwBEFFile = QgsFileWidget(dlgAddBEF)
        self.fwBEFFile.setObjectName("fwBEFFile")
        self.gridLayout.addWidget(self.fwBEFFile, 0, 1, 1, 1)
        self.lblJoinField = QtWidgets.QLabel(dlgAddBEF)
        self.lblJoinField.setObjectName("lblJoinField")
        self.gridLayout.addWidget(self.lblJoinField, 1, 0, 1, 1)
        self.cmbJoinField = QgsFieldComboBox(dlgAddBEF)
        self.cmbJoinField.setObjectName("cmbJoinField")
        self.gridLayout.addWidget(self.cmbJoinField, 1, 1, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(dlgAddBEF)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 3, 0, 1, 2)
        self.gbxFields = QtWidgets.QGroupBox(dlgAddBEF)
        self.gbxFields.setObjectName("gbxFields")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.gbxFields)
        self.verticalLayout.setObjectName("verticalLayout")
        self.vwFields = QtWidgets.QTableView(self.gbxFields)
        self.vwFields.setObjectName("vwFields")
        self.verticalLayout.addWidget(self.vwFields)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnSelectAll = QtWidgets.QPushButton(self.gbxFields)
        self.btnSelectAll.setObjectName("btnSelectAll")
        self.horizontalLayout.addWidget(self.btnSelectAll)
        self.btnSelectNone = QtWidgets.QPushButton(self.gbxFields)
        self.btnSelectNone.setObjectName("btnSelectNone")
        self.horizontalLayout.addWidget(self.btnSelectNone)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout.addWidget(self.gbxFields, 2, 0, 1, 2)

        self.retranslateUi(dlgAddBEF)
        self.buttonBox.accepted.connect(dlgAddBEF.accept) # type: ignore
        self.buttonBox.rejected.connect(dlgAddBEF.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(dlgAddBEF)

    def retranslateUi(self, dlgAddBEF):
        _translate = QtCore.QCoreApplication.translate
        dlgAddBEF.setWindowTitle(_translate("dlgAddBEF", "Choose Block Equivalency File"))
        self.lblBEFFile.setText(_translate("dlgAddBEF", "Block Equivalency File"))
        self.fwBEFFile.setFilter(_translate("dlgAddBEF", "*.csv;*.txt;*.xls;*.xlsx;*.shp"))
        self.lblJoinField.setText(_translate("dlgAddBEF", "Join Field"))
        self.gbxFields.setTitle(_translate("dlgAddBEF", "Add Fields"))
        self.btnSelectAll.setText(_translate("dlgAddBEF", "Select All"))
        self.btnSelectNone.setText(_translate("dlgAddBEF", "Select None"))
from qgsfieldcombobox import QgsFieldComboBox
from qgsfilewidget import QgsFileWidget
