# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/stuart/Source/redist_project/ui/WzpAddFields.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_wzpAddFields(object):
    def setupUi(self, wzpAddFields):
        wzpAddFields.setObjectName("wzpAddFields")
        wzpAddFields.resize(400, 300)
        self.horizontalLayout = QtWidgets.QHBoxLayout(wzpAddFields)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lvSource = QtWidgets.QListView(wzpAddFields)
        self.lvSource.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.lvSource.setDragEnabled(True)
        self.lvSource.setDragDropMode(QtWidgets.QAbstractItemView.DragOnly)
        self.lvSource.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.lvSource.setAlternatingRowColors(True)
        self.lvSource.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.lvSource.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.lvSource.setObjectName("lvSource")
        self.horizontalLayout.addWidget(self.lvSource)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.btnAdd = QtWidgets.QPushButton(wzpAddFields)
        self.btnAdd.setObjectName("btnAdd")
        self.verticalLayout_2.addWidget(self.btnAdd)
        self.btnAddAll = QtWidgets.QPushButton(wzpAddFields)
        self.btnAddAll.setObjectName("btnAddAll")
        self.verticalLayout_2.addWidget(self.btnAddAll)
        spacerItem1 = QtWidgets.QSpacerItem(20, 80, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.btnRemoveAll = QtWidgets.QPushButton(wzpAddFields)
        self.btnRemoveAll.setEnabled(False)
        self.btnRemoveAll.setObjectName("btnRemoveAll")
        self.verticalLayout_2.addWidget(self.btnRemoveAll)
        self.btnRemove = QtWidgets.QPushButton(wzpAddFields)
        self.btnRemove.setEnabled(False)
        self.btnRemove.setObjectName("btnRemove")
        self.verticalLayout_2.addWidget(self.btnRemove)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.lvDest = QtWidgets.QListView(wzpAddFields)
        self.lvDest.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.lvDest.setDragEnabled(True)
        self.lvDest.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.lvDest.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.lvDest.setAlternatingRowColors(True)
        self.lvDest.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.lvDest.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.lvDest.setObjectName("lvDest")
        self.horizontalLayout.addWidget(self.lvDest)

        self.retranslateUi(wzpAddFields)
        QtCore.QMetaObject.connectSlotsByName(wzpAddFields)

    def retranslateUi(self, wzpAddFields):
        _translate = QtCore.QCoreApplication.translate
        wzpAddFields.setWindowTitle(_translate("wzpAddFields", "WizardPage"))
        wzpAddFields.setTitle(_translate("wzpAddFields", "Select Demographic Fields"))
        self.btnAdd.setText(_translate("wzpAddFields", ">"))
        self.btnAddAll.setText(_translate("wzpAddFields", ">>"))
        self.btnRemoveAll.setText(_translate("wzpAddFields", "<<"))
        self.btnRemove.setText(_translate("wzpAddFields", "<"))
