# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/stuart/Source/redist_project/ui/WzpGeography.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_wzpGeography(object):
    def setupUi(self, wzpGeography):
        wzpGeography.setObjectName("wzpGeography")
        wzpGeography.resize(421, 300)
        self.gridLayout = QtWidgets.QGridLayout(wzpGeography)
        self.gridLayout.setObjectName("gridLayout")
        self.lblState = QtWidgets.QLabel(wzpGeography)
        self.lblState.setObjectName("lblState")
        self.gridLayout.addWidget(self.lblState, 1, 0, 1, 1)
        self.cmbState = QtWidgets.QComboBox(wzpGeography)
        self.cmbState.setObjectName("cmbState")
        self.gridLayout.addWidget(self.cmbState, 1, 1, 1, 2)
        self.gbxSubdivision = QtWidgets.QGroupBox(wzpGeography)
        self.gbxSubdivision.setEnabled(True)
        self.gbxSubdivision.setObjectName("gbxSubdivision")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gbxSubdivision)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.rbSubdivision = QtWidgets.QRadioButton(self.gbxSubdivision)
        self.rbSubdivision.setObjectName("rbSubdivision")
        self.gridLayout_2.addWidget(self.rbSubdivision, 1, 0, 1, 2)
        self.lblSubdivisionName = QtWidgets.QLabel(self.gbxSubdivision)
        self.lblSubdivisionName.setEnabled(True)
        self.lblSubdivisionName.setObjectName("lblSubdivisionName")
        self.gridLayout_2.addWidget(self.lblSubdivisionName, 3, 0, 1, 1)
        self.lblSubdivisionGeography = QtWidgets.QLabel(self.gbxSubdivision)
        self.lblSubdivisionGeography.setEnabled(True)
        self.lblSubdivisionGeography.setObjectName("lblSubdivisionGeography")
        self.gridLayout_2.addWidget(self.lblSubdivisionGeography, 2, 0, 1, 1)
        self.cmbSubdivisionGeography = QtWidgets.QComboBox(self.gbxSubdivision)
        self.cmbSubdivisionGeography.setEnabled(True)
        self.cmbSubdivisionGeography.setObjectName("cmbSubdivisionGeography")
        self.gridLayout_2.addWidget(self.cmbSubdivisionGeography, 2, 1, 1, 1)
        self.cmbSubdivisionName = QtWidgets.QComboBox(self.gbxSubdivision)
        self.cmbSubdivisionName.setEnabled(True)
        self.cmbSubdivisionName.setObjectName("cmbSubdivisionName")
        self.gridLayout_2.addWidget(self.cmbSubdivisionName, 3, 1, 1, 1)
        self.rbEntireState = QtWidgets.QRadioButton(self.gbxSubdivision)
        self.rbEntireState.setObjectName("rbEntireState")
        self.gridLayout_2.addWidget(self.rbEntireState, 0, 0, 1, 2)
        self.gridLayout.addWidget(self.gbxSubdivision, 2, 0, 1, 3)
        self.lbDecennial = QtWidgets.QLabel(wzpGeography)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbDecennial.sizePolicy().hasHeightForWidth())
        self.lbDecennial.setSizePolicy(sizePolicy)
        self.lbDecennial.setObjectName("lbDecennial")
        self.gridLayout.addWidget(self.lbDecennial, 0, 0, 1, 1)
        self.cmDecennial = QtWidgets.QComboBox(wzpGeography)
        self.cmDecennial.setObjectName("cmDecennial")
        self.gridLayout.addWidget(self.cmDecennial, 0, 1, 1, 2)
        self.lblState.setBuddy(self.cmbState)
        self.lblSubdivisionName.setBuddy(self.cmbSubdivisionName)
        self.lblSubdivisionGeography.setBuddy(self.cmbSubdivisionGeography)
        self.lbDecennial.setBuddy(self.cmDecennial)

        self.retranslateUi(wzpGeography)
        self.rbSubdivision.toggled['bool'].connect(self.lblSubdivisionGeography.setEnabled) # type: ignore
        self.rbSubdivision.toggled['bool'].connect(self.cmbSubdivisionGeography.setEnabled) # type: ignore
        self.rbSubdivision.toggled['bool'].connect(self.lblSubdivisionName.setEnabled) # type: ignore
        self.rbSubdivision.toggled['bool'].connect(self.cmbSubdivisionName.setEnabled) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(wzpGeography)
        wzpGeography.setTabOrder(self.cmbState, self.rbEntireState)
        wzpGeography.setTabOrder(self.rbEntireState, self.rbSubdivision)
        wzpGeography.setTabOrder(self.rbSubdivision, self.cmbSubdivisionGeography)
        wzpGeography.setTabOrder(self.cmbSubdivisionGeography, self.cmbSubdivisionName)

    def retranslateUi(self, wzpGeography):
        _translate = QtCore.QCoreApplication.translate
        wzpGeography.setWindowTitle(_translate("wzpGeography", "WizardPage"))
        self.lblState.setText(_translate("wzpGeography", "State"))
        self.cmbState.setPlaceholderText(_translate("wzpGeography", "Choose state"))
        self.gbxSubdivision.setTitle(_translate("wzpGeography", "District Geography"))
        self.rbSubdivision.setText(_translate("wzpGeography", "Subdivision"))
        self.lblSubdivisionName.setText(_translate("wzpGeography", "Subdivision Name"))
        self.lblSubdivisionGeography.setText(_translate("wzpGeography", "Subdivision Geography"))
        self.cmbSubdivisionGeography.setPlaceholderText(_translate("wzpGeography", "District a subdivision"))
        self.cmbSubdivisionName.setPlaceholderText(_translate("wzpGeography", "Select subdivision to district"))
        self.rbEntireState.setText(_translate("wzpGeography", "Entire State"))
        self.lbDecennial.setText(_translate("wzpGeography", "Decennial Census"))
