# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/stuart/Source/redist_project/ui/WzpPlanParameters.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_wzpPlanParameters(object):
    def setupUi(self, wzpPlanParameters):
        wzpPlanParameters.setObjectName("wzpPlanParameters")
        wzpPlanParameters.resize(400, 300)
        self.gridLayout = QtWidgets.QGridLayout(wzpPlanParameters)
        self.gridLayout.setObjectName("gridLayout")
        self.lblNumDistricts = QtWidgets.QLabel(wzpPlanParameters)
        self.lblNumDistricts.setObjectName("lblNumDistricts")
        self.gridLayout.addWidget(self.lblNumDistricts, 0, 0, 1, 1)
        self.sbxNumDistricts = QtWidgets.QSpinBox(wzpPlanParameters)
        self.sbxNumDistricts.setMinimum(2)
        self.sbxNumDistricts.setMaximum(1000)
        self.sbxNumDistricts.setObjectName("sbxNumDistricts")
        self.gridLayout.addWidget(self.sbxNumDistricts, 0, 2, 1, 1)
        self.lblNumSeats = QtWidgets.QLabel(wzpPlanParameters)
        self.lblNumSeats.setObjectName("lblNumSeats")
        self.gridLayout.addWidget(self.lblNumSeats, 1, 0, 1, 1)
        self.sbxNumSeats = QtWidgets.QSpinBox(wzpPlanParameters)
        self.sbxNumSeats.setMinimum(2)
        self.sbxNumSeats.setMaximum(1000)
        self.sbxNumSeats.setProperty("value", 2)
        self.sbxNumSeats.setObjectName("sbxNumSeats")
        self.gridLayout.addWidget(self.sbxNumSeats, 1, 2, 1, 1)
        self.lblMaxDeviation = QtWidgets.QLabel(wzpPlanParameters)
        self.lblMaxDeviation.setObjectName("lblMaxDeviation")
        self.gridLayout.addWidget(self.lblMaxDeviation, 2, 0, 1, 1)
        self.cbIncludeVAP = QtWidgets.QCheckBox(wzpPlanParameters)
        self.cbIncludeVAP.setObjectName("cbIncludeVAP")
        self.gridLayout.addWidget(self.cbIncludeVAP, 3, 0, 1, 1)
        self.cbIncludeCVAP = QtWidgets.QCheckBox(wzpPlanParameters)
        self.cbIncludeCVAP.setObjectName("cbIncludeCVAP")
        self.gridLayout.addWidget(self.cbIncludeCVAP, 4, 0, 1, 1)
        self.cbIncludeReg = QtWidgets.QCheckBox(wzpPlanParameters)
        self.cbIncludeReg.setObjectName("cbIncludeReg")
        self.gridLayout.addWidget(self.cbIncludeReg, 5, 0, 1, 2)
        self.sbxMaxDeviation = QtWidgets.QDoubleSpinBox(wzpPlanParameters)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbxMaxDeviation.sizePolicy().hasHeightForWidth())
        self.sbxMaxDeviation.setSizePolicy(sizePolicy)
        self.sbxMaxDeviation.setSingleStep(0.1)
        self.sbxMaxDeviation.setObjectName("sbxMaxDeviation")
        self.gridLayout.addWidget(self.sbxMaxDeviation, 2, 2, 1, 1)
        self.lblNumDistricts.setBuddy(self.sbxNumDistricts)
        self.lblNumSeats.setBuddy(self.sbxNumSeats)

        self.retranslateUi(wzpPlanParameters)
        QtCore.QMetaObject.connectSlotsByName(wzpPlanParameters)
        wzpPlanParameters.setTabOrder(self.sbxNumDistricts, self.sbxNumSeats)
        wzpPlanParameters.setTabOrder(self.sbxNumSeats, self.sbxMaxDeviation)
        wzpPlanParameters.setTabOrder(self.sbxMaxDeviation, self.cbIncludeVAP)
        wzpPlanParameters.setTabOrder(self.cbIncludeVAP, self.cbIncludeCVAP)
        wzpPlanParameters.setTabOrder(self.cbIncludeCVAP, self.cbIncludeReg)

    def retranslateUi(self, wzpPlanParameters):
        _translate = QtCore.QCoreApplication.translate
        wzpPlanParameters.setWindowTitle(_translate("wzpPlanParameters", "WizardPage"))
        self.lblNumDistricts.setText(_translate("wzpPlanParameters", "&Number of Districts"))
        self.sbxNumDistricts.setToolTip(_translate("wzpPlanParameters", "Enter the total number of districts in your plan"))
        self.lblNumSeats.setText(_translate("wzpPlanParameters", "Number of &Seats"))
        self.sbxNumSeats.setToolTip(_translate("wzpPlanParameters", "Enter the number of seats that are elected from the districts in this plan"))
        self.lblMaxDeviation.setText(_translate("wzpPlanParameters", "Maximum Deviation"))
        self.cbIncludeVAP.setText(_translate("wzpPlanParameters", "Include VAP"))
        self.cbIncludeCVAP.setText(_translate("wzpPlanParameters", "Include CVAP"))
        self.cbIncludeReg.setText(_translate("wzpPlanParameters", "Include Registered Voters"))
        self.sbxMaxDeviation.setPrefix(_translate("wzpPlanParameters", "±"))
        self.sbxMaxDeviation.setSuffix(_translate("wzpPlanParameters", "%"))
