# -*- coding: utf-8 -*-
"""QGIS Redistricting Project Plugin - Field definitions

        begin                : 2024-01-24
        git sha              : $Format:%H$
        copyright            : (C) 2024 by Cryptodira
        email                : stuart@cryptodira.org

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 3 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 *   This program is distributed in the hope that it will be useful, but   *
 *   WITHOUT ANY WARRANTY; without even the implied warranty of            *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the          *
 *   GNU General Public License for more details. You should have          *
 *   received a copy of the GNU General Public License along with this     *
 *   program. If not, see <http://www.gnu.org/licenses/>.                  *
 *                                                                         *
 ***************************************************************************/
"""
from typing import TypedDict

from .utils import tr


class FieldDict(TypedDict):
    caption: str
    sum: bool
    pctbase: str
    tooltip: str


# pylint: disable=line-too-long
pop_fields: dict[str, FieldDict] = {
    #    "pop_total": {"caption": tr("Total Population"), "sum": True, "pctbase": None},
    "pop_white": {"caption": tr("White"), "sum": True, "pctbase": "pop_total",
                  "tooltip": tr("Total Hispanic and non-Hispanic single-race white population")},
    "pop_black": {"caption": tr("Black"), "sum": True, "pctbase": "pop_total",
                  "tooltip": tr("Total Hispanic and non-Hispanic single-race Black population")},
    "pop_ap_black": {"caption": tr("AP Black"), "sum": True, "pctbase": "pop_total",
                     "tooltip": tr("Total Hispanic and non-Hispanic any part Black population")},
    "pop_aiakn": {"caption": tr("Native"), "sum": True, "pctbase": "pop_total",
                  "tooltip": tr("Total Hispanic and non-Hispanic single-race American Indian and Alaska Native population")},
    "pop_ap_aiakn": {"caption": tr("AP Native"), "sum": True, "pctbase": "pop_total",
                     "tooltip": tr("Total Hispanic and non-Hispanic any part American Indian and Alaska Native population")},
    "pop_asian": {"caption": tr("Asian"), "sum": True, "pctbase": "pop_total",
                  "tooltip": tr("Total Hispanic and non-Hispanic single-race Asian population")},
    "pop_ap_asian": {"caption": tr("AP Asian"), "sum": True, "pctbase": "pop_total",
                     "tooltip": tr("Total Hispanic and non-Hispanic any part Asian population")},
    "pop_hawpi": {"caption": tr("Hawaiian/PI"), "sum": True, "pctbase": "pop_total",
                  "tooltip": tr("Total Hispanic and non-Hispanic single-race Native Hawaiian and Pacific Islander population")},
    "pop_ap_hawpi": {"caption": tr("AP Hawaiian/PI"), "sum": True, "pctbase": "pop_total",
                     "tooltip": tr("Total Hispanic and non-Hispanic any part Native Hawaiian and Pacific Islander population")},
    "pop_other_singlerace": {"caption": tr("Other Single Race"), "sum": True, "pctbase": "pop_total",
                             "tooltip": tr("Total Hispanic and non-Hispanic population of some other single race")},
    "pop_multiracial": {"caption": tr("Multiracial"), "sum": True, "pctbase": "pop_total",
                        "tooltip": tr("Total Hispanic and non-Hispanic population of more than one race")},
    "pop_hispanic": {"caption": tr("Hispanic/Latino"), "sum": True, "pctbase": "pop_total",
                     "tooltip": tr("Total Hispanic or Latino/a/x population of any race")},
    "pop_nonhispanic": {"caption": tr("Non-Hispanic/Latino"), "sum": True, "pctbase": "pop_total",
                        "tooltip": tr("Total non-Hispanic or Latino/a/x population of any race")},
    "pop_nh_white": {"caption": tr("NH White"), "sum": True, "pctbase": "pop_total",
                     "tooltip": tr("Total non-Hispanic single-race white population")},
    "pop_nh_black": {"caption": tr("NH Black"), "sum": True, "pctbase": "pop_total",
                     "tooltip": tr("Total non-Hispanic single-race Black population")},
    "pop_nh_ap_black": {"caption": tr("NH AP Black"), "sum": True, "pctbase": "pop_total",
                        "tooltip": tr("Total non-Hispanic any part Black population")},
    "pop_nh_aiakn": {"caption": tr("NH Native"), "sum": True, "pctbase": "pop_total",
                     "tooltip": tr("Total non-Hispanic single-race American Indian and Alaska Native population")},
    "pop_nh_ap_aiakn": {"caption": tr("NH AP Native"), "sum": True, "pctbase": "pop_total",
                        "tooltip": tr("Total non-Hispanic any part American Indian and Alaska Native population")},
    "pop_nh_asian": {"caption": tr("NH Asian"), "sum": True, "pctbase": "pop_total",
                     "tooltip": tr("Total non-Hispanic single-race Asian population")},
    "pop_nh_ap_asian": {"caption": tr("NH AP Asian"), "sum": True, "pctbase": "pop_total",
                        "tooltip": tr("Total non-Hispanic any part Asian population")},
    "pop_nh_hawpi": {"caption": tr("NH Hawaiian/PI"), "sum": True, "pctbase": "pop_total",
                     "tooltip": tr("Total non-Hispanic single-race Native Hawaiian and Pacific Islander population")},
    "pop_nh_ap_hawpi": {"caption": tr("NH AP Hawaiian/PI"), "sum": True, "pctbase": "pop_total",
                        "tooltip": tr("Total non-Hispanic any part Native Hawaiian and Pacific Islander population")},
    "pop_nh_other_singlerace": {"caption": tr("NH Other Single Race"), "sum": True, "pctbase": "pop_total",
                                "tooltip": tr("Total non-Hispanic population of another single race")},
    "pop_nh_multiracial": {"caption": tr("NH Multiracial"), "sum": True, "pctbase": "pop_total",
                           "tooltip": tr("Total non-Hispanic population of more than one race")}, }

pop_combination_fields: dict[str, FieldDict] = {
    "pop_black_white": {"caption": tr("Black+White"), "sum": True, "pctbase": "pop_total",
                        "tooltip": tr("Total Hispanic and non-Hispanic population of Black and white races")},
    "pop_black_aiakn": {"caption": tr("Black+Native"), "sum": True, "pctbase": "pop_total",
                        "tooltip": tr("Total Hispanic and non-Hispanic population of Black and American Indian or Alaska Native races")},
    "pop_black_asian": {"caption": tr("Black+Asian"), "sum": True, "pctbase": "pop_total",
                        "tooltip": tr("Total Hispanic and non-Hispanic population of Black and Asian races")},
    "pop_black_hawpi": {"caption": tr("Black+Hawaiian/PI"), "sum": True, "pctbase": "pop_total",
                        "tooltip": tr("Total Hispanic and non-Hispanic population of Black and Native Hawaiian or Pacific Islander races")},
    "pop_black_other": {"caption": tr("Black+Other"), "sum": True, "pctbase": "pop_total",
                        "tooltip": tr("Total Hispanic and non-Hispanic population of Black and some unspecified other single race")},
    "pop_black_white_aiakn": {"caption": tr("Black+White+Native"), "sum": True, "pctbase": "pop_total",
                              "tooltip": tr("Total Hispanic and non-Hispanic population of Black, white and American Indian or Alaska Native races")},
    "pop_white_other": {"caption": tr("White+Other"), "sum": True, "pctbase": "pop_total",
                        "tooltip": tr("Total Hispanic and non-Hispanic population of white and some unspecified other single race")},
    "pop_aiakn_white": {"caption": tr("Native+White"), "sum": True, "pctbase": "pop_total",
                        "tooltip": tr("Total Hispanic and non-Hispanic population of Amrican Indian or Alsaska Native and white races")},
    "pop_aiakn_asian": {"caption": tr("Native+Asian"), "sum": True, "pctbase": "pop_total",
                        "tooltip": tr("Total Hispanic and non-Hispanic population of Amrican Indian or Alsaska Native and Asian races")},
    "pop_aiakn_hawpi": {"caption": tr("Native+Hawaiian/PI"), "sum": True, "pctbase": "pop_total",
                        "tooltip": tr("Total Hispanic and non-Hispanic population of Amrican Indian or Alsaska Native and Native Hawaiian or Pacific Islander races")},
    "pop_aiakn_other": {"caption": tr("Native+Other"), "sum": True, "pctbase": "pop_total",
                        "tooltip": tr("Total Hispanic and non-Hispanic population of Amrican Indian or Alsaska Native and some unspecified other race")},
    "pop_asian_white": {"caption": tr("Asian+White"), "sum": True, "pctbase": "pop_total",
                        "tooltip": tr("Total Hispanic and non-Hispanic population of Asian and white races")},
    "pop_asian_hawpi": {"caption": tr("Asian+Hawaiian/PI"), "sum": True, "pctbase": "pop_total",
                        "tooltip": tr("Total Hispanic and non-Hispanic population of Asian and Native Hawaiian or Pacific Islander races")},
    "pop_asian_other": {"caption": tr("Asian+Other"), "sum": True, "pctbase": "pop_total",
                        "tooltip": tr("Total Hispanic and non-Hispanic population of Asian and some unspecified other race")},
    "pop_hawpi_white": {"caption": tr("Hawaiian/PI+White"), "sum": True, "pctbase": "pop_total",
                        "tooltip": tr("Total Hispanic and non-Hispanic population of Native Hawaiian or Pacific Islander and white races")},
    "pop_hawpi_other": {"caption": tr("Hawaiian/PI+Other"), "sum": True, "pctbase": "pop_total",
                        "tooltip": tr("Total Hispanic and non-Hispanic population of Native Hawaiian or Pacific Islander and some unspecified other race")},

    "pop_nh_black_white": {"caption": tr("NH Black+White"), "sum": True, "pctbase": "pop_total",
                           "tooltip": tr("Total Hispanic and non-Hispanic population of Black and white races")},
    "pop_nh_black_aiakn": {"caption": tr("NH Black+Native"), "sum": True, "pctbase": "pop_total",
                           "tooltip": tr("Total Hispanic and non-Hispanic population of Black and American Indian or Alaska Native races")},
    "pop_nh_black_asian": {"caption": tr("NH Black+Asian"), "sum": True, "pctbase": "pop_total",
                           "tooltip": tr("Total Hispanic and non-Hispanic population of Black and Asian races")},
    "pop_nh_black_hawpi": {"caption": tr("NH Black+Hawaiian/PI"), "sum": True, "pctbase": "pop_total",
                           "tooltip": tr("Total Hispanic and non-Hispanic population of Black and Native Hawaiian or Pacific Islander races")},
    "pop_nh_black_other": {"caption": tr("NH Black+Other"), "sum": True, "pctbase": "pop_total",
                           "tooltip": tr("Total Hispanic and non-Hispanic population of Black and some unspecified other single race")},
    "pop_nh_black_white_aiakn": {"caption": tr("NH Black+White+Native"), "sum": True, "pctbase": "pop_total",
                                 "tooltip": tr("Total Hispanic and non-Hispanic population of Black, white and American Indian or Alaska Native races")},
    "pop_nh_white_other": {"caption": tr("NH White+Other"), "sum": True, "pctbase": "pop_total",
                           "tooltip": tr("Total Hispanic and non-Hispanic population of white and some unspecified other single race")},
    "pop_nh_aiakn_white": {"caption": tr("NH Native+White"), "sum": True, "pctbase": "pop_total",
                           "tooltip": tr("Total Hispanic and non-Hispanic population of Amrican Indian or Alsaska Native and white races")},
    "pop_nh_aiakn_asian": {"caption": tr("NH Native+Asian"), "sum": True, "pctbase": "pop_total",
                           "tooltip": tr("Total Hispanic and non-Hispanic population of Amrican Indian or Alsaska Native and Asian races")},
    "pop_nh_aiakn_hawpi": {"caption": tr("NH Native+Hawaiian/PI"), "sum": True, "pctbase": "pop_total",
                           "tooltip": tr("Total Hispanic and non-Hispanic population of Amrican Indian or Alsaska Native and Native Hawaiian or Pacific Islander races")},
    "pop_nh_aiakn_other": {"caption": tr("NH Native+Other"), "sum": True, "pctbase": "pop_total",
                           "tooltip": tr("Total Hispanic and non-Hispanic population of Amrican Indian or Alsaska Native and some unspecified other race")},
    "pop_nh_asian_white": {"caption": tr("NH Asian+White"), "sum": True, "pctbase": "pop_total",
                           "tooltip": tr("Total Hispanic and non-Hispanic population of Asian and white races")},
    "pop_nh_asian_hawpi": {"caption": tr("NH Asian+Hawaiian/PI"), "sum": True, "pctbase": "pop_total",
                           "tooltip": tr("Total Hispanic and non-Hispanic population of Asian and Native Hawaiian or Pacific Islander races")},
    "pop_nh_asian_other": {"caption": tr("NH Asian+Other"), "sum": True, "pctbase": "pop_total",
                           "tooltip": tr("Total Hispanic and non-Hispanic population of Asian and some unspecified other race")},
    "pop_nh_hawpi_white": {"caption": tr("NH Hawaiian/PI+White"), "sum": True, "pctbase": "pop_total",
                           "tooltip": tr("Total Hispanic and non-Hispanic population of Native Hawaiian or Pacific Islander and white races")},
    "pop_nh_hawpi_other": {"caption": tr("NH Hawaiian/PI+Other"), "sum": True, "pctbase": "pop_total",
                           "tooltip": tr("Total Hispanic and non-Hispanic population of Native Hawaiian or Pacific Islander and some unspecified other race")},
}

vap_fields: dict[str, FieldDict] = {
    #    "vap_total": {"caption": tr("Total VAP"), "sum": True, "pctbase": None},
    "vap_white": {"caption": tr("WVAP"), "sum": True, "pctbase": "vap_total",
                  "tooltip": tr("Voting age single-race white population, Hispanic and non-Hispanic")},
    "vap_black": {"caption": tr("BVAP"), "sum": True, "pctbase": "vap_total",
                  "tooltip": tr("Voting age single-race Black population, Hispanic and non-Hispanic")},
    "vap_ap_black": {"caption": tr("AP BVAP"), "sum": True, "pctbase": "vap_total",
                     "tooltip": tr("Voting age any part Black population, Hispanic and non-Hispanic")},
    "vap_aiakn": {"caption": tr("NVAP"), "sum": True, "pctbase": "vap_total",
                  "tooltip": tr("Voting age single-race American Indian or Alaska Native population, Hispanic and non-Hispanic")},
    "vap_ap_aiakn": {"caption": tr("AP NVAP"), "sum": True, "pctbase": "vap_total",
                     "tooltip": tr("Voting age any part American Indian or Alaska Native population, Hispanic and non-Hispanic")},
    "vap_asian": {"caption": tr("AVAP"), "sum": True, "pctbase": "vap_total",
                  "tooltip": tr("Voting age single-race Asian population, Hispanic and non-Hispanic")},
    "vap_ap_asian": {"caption": tr("AP AVAP"), "sum": True, "pctbase": "vap_total",
                     "tooltip": tr("Voting age any part Asian population, Hispanic and non-Hispanic")},
    "vap_hawpi": {"caption": tr("NHPIVAP"), "sum": True, "pctbase": "vap_total",
                  "tooltip": tr("Voting age single-race Native Hawaiian or Pacific Islander population, Hispanic and non-Hispanic")},
    "vap_ap_hawpi": {"caption": tr("AP NHPIVAP"), "sum": True, "pctbase": "vap_total",
                     "tooltip": tr("Voting age any part Native Hawaiian or Pacific Islander population, Hispanic and non-Hispanic")},
    "vap_other_singlerace": {"caption": tr("OSR_VAP"), "sum": True, "pctbase": "vap_total",
                             "tooltip": tr("Voting age population of some other single race, Hispanic and non-Hispanic")},
    "vap_multiracial": {"caption": tr("MR VAP"), "sum": True, "pctbase": "vap_total",
                        "tooltip": tr("Voting age population of more than one race, Hispanic and non-Hispanic")},
    "vap_hispanic": {"caption": tr("HVAP"), "sum": True, "pctbase": "vap_total",
                     "tooltip": tr("Voting age Hispanic or Latino/a/x population")},
    "vap_nonhispanic": {"caption": tr("NH VAP"), "sum": True, "pctbase": "vap_total",
                        "tooltip": tr("Voting age population that is not Hispanic or Latino/a/x")},
    "vap_nh_white": {"caption": tr("NH WVAP"), "sum": True, "pctbase": "vap_total",
                     "tooltip": tr("Voting age non-Hispanic single-race white population")},
    "vap_nh_black": {"caption": tr("NH BVAP"), "sum": True, "pctbase": "vap_total",
                     "tooltip": tr("Voting age non-Hispanic single-race Black population")},
    "vap_nh_ap_black": {"caption": tr("NH AP BVAP"), "sum": True, "pctbase": "vap_total",
                        "tooltip": tr("Voting age non-Hispanic any part Black population")},
    "vap_nh_black_black_white": {"caption": "NH B&B+W VAP", "sum": True, "pctbase": "vap_total",
                                 "tooltip": tr("Voting age non-Hispanic Black plus Black and white in combination population (aka DOJ Black)")},
    "vap_nh_aiakn": {"caption": tr("NH NVAP"), "sum": True, "pctbase": "vap_total",
                     "tooltip": tr("Voting age non-Hispanic single-race American Indian or Alaska Native population")},
    "vap_nh_ap_aiakn": {"caption": tr("NH AP NVAP"), "sum": True, "pctbase": "vap_total",
                        "tooltip": tr("Voting age non-Hispanic any part American Indian or Alaska Native population")},
    "vap_nh_asian": {"caption": tr("NH AVAP"), "sum": True, "pctbase": "vap_total",
                     "tooltip": tr("Voting age non-Hispanic single-race Asian population")},
    "vap_nh_ap_asian": {"caption": tr("NH AP AVAP"), "sum": True, "pctbase": "vap_total",
                        "tooltip": tr("Voting age non-Hispanic any part Asian population")},
    "vap_nh_hawpi": {"caption": tr("NH NHPIVAP"), "sum": True, "pctbase": "vap_total",
                     "tooltip": tr("Voting age non-Hispanic single-race Native Hawaiian or Pacific Islander population")},
    "vap_nh_ap_hawpi": {"caption": tr("NH AP NHPIVAP"), "sum": True, "pctbase": "vap_total",
                        "tooltip": tr("Voting age non-Hispanic any part Native Hawaiian or Pacific Islander population")},
    "vap_nh_other_singlerace": {"caption": tr("NH OVAP"), "sum": True, "pctbase": "vap_total",
                                "tooltip": tr("Voting age non-Hispanic population of some other single race")},
    "vap_nh_multiracial": {"caption": tr("NH MRVAP"), "sum": True, "pctbase": "vap_total",
                           "tooltip": tr("Voting age non-Hispanic population of more than one race")},
}

vap_combination_fields: dict[str, FieldDict] = {
    "vap_black_white": {"caption": tr("B+W VAP"), "sum": True, "pctbase": "vap_total",
                        "tooltip": ""},
    "vap_black_aiakn": {"caption": tr("B+N VAP"), "sum": True, "pctbase": "vap_total",
                        "tooltip": ""},
    "vap_black_asian": {"caption": tr("B+A VAP"), "sum": True, "pctbase": "vap_total",
                        "tooltip": ""},
    "vap_black_hawpi": {"caption": tr("B+NHPIVAP"), "sum": True, "pctbase": "vap_total",
                        "tooltip": ""},
    "vap_black_other": {"caption": tr("B+O VAP"), "sum": True, "pctbase": "vap_total",
                        "tooltip": ""},
    "vap_black_white_aiakn": {"caption": tr("B+W+N VAP"), "sum": True, "pctbase": "vap_total",
                              "tooltip": ""},
    "vap_aiakn_white": {"caption": tr("N+W VAP"), "sum": True, "pctbase": "vap_total",
                        "tooltip": ""},
    "vap_aiakn_asian": {"caption": tr("N+A VAP"), "sum": True, "pctbase": "vap_total",
                        "tooltip": ""},
    "vap_aiakn_hawpi": {"caption": tr("N+NHPIVAP"), "sum": True, "pctbase": "vap_total",
                        "tooltip": ""},
    "vap_aiakn_other": {"caption": tr("N+O VAP"), "sum": True, "pctbase": "vap_total",
                        "tooltip": ""},
    "vap_asian_white": {"caption": tr("A+W VAP"), "sum": True, "pctbase": "vap_total",
                        "tooltip": ""},
    "vap_hawpi_white": {"caption": tr("HPI+W VAP"), "sum": True, "pctbase": "vap_total",
                        "tooltip": ""},
    "vap_nh_black_white": {"caption": tr("NH B+W VAP"), "sum": True, "pctbase": "vap_total",
                           "tooltip": ""},
    "vap_nh_black_aiakn": {"caption": tr("NH B+N VAP"), "sum": True, "pctbase": "vap_total",
                           "tooltip": ""},
    "vap_nh_black_asian": {"caption": tr("NH B+A VAP"), "sum": True, "pctbase": "vap_total",
                           "tooltip": ""},
    "vap_nh_black_hawpi": {"caption": tr("NH B+NHPIVAP"), "sum": True, "pctbase": "vap_total",
                           "tooltip": ""},
    "vap_nh_black_other": {"caption": tr("NH B+O VAP"), "sum": True, "pctbase": "vap_total",
                           "tooltip": ""},
    "vap_nh_black_white_aiakn": {"caption": tr("NH B+W+N VAP"), "sum": True, "pctbase": "vap_total",
                                 "tooltip": ""},
    "vap_nh_aiakn_white": {"caption": tr("NH N+W VAP"), "sum": True, "pctbase": "vap_total",
                           "tooltip": ""},
    "vap_nh_aiakn_asian": {"caption": tr("NH N+A VAP"), "sum": True, "pctbase": "vap_total",
                           "tooltip": ""},
    "vap_nh_aiakn_hawpi": {"caption": tr("NH N+NHPIVAP"), "sum": True, "pctbase": "vap_total",
                           "tooltip": ""},
    "vap_nh_aiakn_other": {"caption": tr("NH N+O VAP"), "sum": True, "pctbase": "vap_total",
                           "tooltip": ""},
    "vap_nh_asian_white": {"caption": tr("NH A+W VAP"), "sum": True, "pctbase": "vap_total",
                           "tooltip": ""},
    "vap_nh_hawpi_white": {"caption": tr("NH HPI+W VAP"), "sum": True, "pctbase": "vap_total",
                           "tooltip": ""},
}

gq_fields: dict[str, FieldDict] = {
    "pop_group_quarters_total": {"caption": tr("Group Qtrs Total"), "sum": True, "pctbase": "pop_total",
                                 "tooltip": tr("Total group quarters population")},
    "pop_correctional": {"caption": tr("GQ Correctional"), "sum": True, "pctbase": "pop_total",
                         "tooltip": tr("Population in correctional facilities for adults")},
    "pop_juvenile": {"caption": tr("GQ Juvenile"), "sum": True, "pctbase": "pop_total",
                     "tooltip": tr("Population in juvenile facilities")},
    "pop_nursing": {"caption": tr("GQ Nursing Homes"), "sum": True, "pctbase": "pop_total",
                    "tooltip": tr("Populution in nursing facilities")},
    "pop_other_inst": {"caption": tr("GQ Other Inst."), "sum": True, "pctbase": "pop_total",
                       "tooltip": tr("Population in other institutional facilities")},
    "pop_university": {"caption": tr("GQ University"), "sum": True, "pctbase": "pop_total",
                       "tooltip": tr("College/university student housing population")},
    "pop_military": {"caption": tr("GQ Military"), "sum": True, "pctbase": "pop_total",
                     "tooltip": tr("Military quarters population")},
    "pop_other_noninst": {"caption": tr("GQ Other Noninst."), "sum": True, "pctbase": "pop_total",
                          "tooltip": tr("Population in other non-institutional group-quarters facilities")},
}

cvap_fields: dict[str, FieldDict] = {
    #    "cvap_total": {"caption": tr("Total CVAP"), "sum": True, "pctbase": None},
    #    "cpop_total": {"caption": tr("Total CPOP"), "sum": True, "pctbase": None},
    "cvap_aiakn": {"caption": tr("NCVAP"), "sum": True, "pctbase": "cvap_total",
                   "tooltip": tr("Citizen voting-age American Indian or Native Alaskan population")},
    "cvap_asian": {"caption": tr("ACVAP"), "sum": True, "pctbase": "cvap_total",
                   "tooltip": tr("Citizen voting-age Asian population")},
    "cvap_black": {"caption": tr("BCVAP"), "sum": True, "pctbase": "cvap_total",
                   "tooltip": tr("Citizen voting age Black population")},
    "cvap_hawpi": {"caption": tr("H/PI CVAP"), "sum": True, "pctbase": "cvap_total",
                   "tooltip": tr("Citizen voting-age Native Hawaiian or Pacific Islander population")},
    "cvap_white": {"caption": tr("WCVAP"), "sum": True, "pctbase": "cvap_total",
                   "tooltip": tr("Citizen voting-age white population")},
    "cvap_aiakn_white": {"caption": tr("N+W CVAP"), "sum": True, "pctbase": "cvap_total",
                         "tooltip": tr("American Indian or Alaska Native and white, in combination, citizen voting-age population")},
    "cvap_asian_white": {"caption": tr("A+W CVAP"), "sum": True, "pctbase": "cvap_total",
                         "tooltip": tr("Asian and white, in combination, citizen voting-age population")},
    "cvap_black_white": {"caption": tr("B+W CVAP"), "sum": True, "pctbase": "cvap_total",
                         "tooltip": tr("Black and white, in combination, citizen voting-age population")},
    "cvap_black_aiakn": {"caption": tr("B+N CVAP"), "sum": True, "pctbase": "cvap_total",
                         "tooltip": tr("Black and American Indian or Alaska Native, in combination, citizen voting age population")},
    "cvap_other_multiracial": {"caption": tr("MR CVAP"), "sum": True, "pctbase": "cvap_total",
                               "tooltip": tr("Other multiracial citizen voting-age population")},
    "cvap_hispanic": {"caption": tr("HCVAP"), "sum": True, "pctbase": "cvap_total",
                      "tooltip": tr("Hispanic or Latino/a/x citizen voting-age population")},
    "cvap_nonhispanic": {"caption": tr("NH CVAP"), "sum": True, "pctbase": "cvap_total",
                         "tooltip": tr("Non-Hispanic or Latino/a/x citizen voting-age population")},
    "cvap_ap_aiakn": {"caption": tr("AP NCVAP"), "sum": True, "pctbase": "cvap_total",
                      "tooltip": tr("Single-race and in-combination American Indian or Alaska Native citizen voting-age population")},
    "cvap_ap_black": {"caption": tr("AP BCVAP"), "sum": True, "pctbase": "cvap_total",
                      "tooltip": tr("Single-race and in-combination Black citizen voting-age population")},
    "cvap_ap_asian": {"caption": tr("AP ACVAP"), "sum": True, "pctbase": "cvap_total",
                      "tooltip": tr("Single-race and in-combination Asian citizen voting-age population")},
    "cpop_aiakn": {"caption": tr("NCPOP"), "sum": True, "pctbase": "cpop_total",
                   "tooltip": ""},
    "cpop_asian": {"caption": tr("ACPOP"), "sum": True, "pctbase": "cpop_total",
                   "tooltip": ""},
    "cpop_black": {"caption": tr("BCPOP"), "sum": True, "pctbase": "cpop_total",
                   "tooltip": ""},
    "cpop_hawpi": {"caption": tr("H/PI CPOP"), "sum": True, "pctbase": "cpop_total",
                   "tooltip": ""},
    "cpop_white": {"caption": tr("WCPOP"), "sum": True, "pctbase": "cpop_total",
                   "tooltip": ""},
    "cpop_aiakn_white": {"caption": tr("N+W CPOP"), "sum": True, "pctbase": "cpop_total",
                         "tooltip": ""},
    "cpop_asian_white": {"caption": tr("A+W CPOP"), "sum": True, "pctbase": "cpop_total",
                         "tooltip": ""},
    "cpop_black_white": {"caption": tr("B+W CPOP"), "sum": True, "pctbase": "cpop_total",
                         "tooltip": ""},
    "cpop_black_aiakn": {"caption": tr("B+N CPOP"), "sum": True, "pctbase": "cpop_total",
                         "tooltip": ""},
    "cpop_other_multiracial": {"caption": tr("MR CPOP"), "sum": True, "pctbase": "cpop_total",
                               "tooltip": ""},
    "cpop_hispanic": {"caption": tr("HCPOP"), "sum": True, "pctbase": "cpop_total",
                      "tooltip": ""},
    "cpop_nonhispanic": {"caption": tr("NH CPOP"), "sum": True, "pctbase": "cpop_total",
                         "tooltip": ""},
    "cpop_ap_aiakn": {"caption": tr("AP NCPOP"), "sum": True, "pctbase": "cpop_total",
                      "tooltip": ""},
    "cpop_ap_black": {"caption": tr("AP BCPOP"), "sum": True, "pctbase": "cpop_total",
                      "tooltip": ""},
    "cpop_ap_asian": {"caption": tr("AP ACPOP"), "sum": True, "pctbase": "cpop_total",
                      "tooltip": ""},
}

vr_fields: dict[str, FieldDict] = {
    #    "reg_total": {"caption": tr("Total Reg."), "sum": True, "pctbase": ""},
    "reg_party_democrat": {"caption": tr("Dem. Reg."), "sum": True, "pctbase": "reg_total",
                           "tooltip": tr("Registered Democrats")},
    "reg_party_republican": {"caption": tr("Rep. Reg"), "sum": True, "pctbase": "reg_total",
                             "tooltip": tr("Registered Republicans")},
    "reg_party_no_party": {"caption": tr("NP Reg"), "sum": True, "pctbase": "reg_total",
                           "tooltip": tr("Registered voters not affiliated with a party")},
    "reg_party_other": {"caption": tr("Oth. P. Reg."), "sum": True, "pctbase": "reg_total",
                        "tooltip": tr("Voters registered with another party")},
    "reg_party_unknown": {"caption": tr("Unk. P. Reg."), "sum": True, "pctbase": "reg_total",
                          "tooltip": tr("Voters whose party affiliation is unknown")},
    "reg_white": {"caption": tr("White Reg."), "sum": True, "pctbase": "reg_total",
                  "tooltip": tr("White registered voter population")},
    "reg_hispanic": {"caption": tr("Hisp./Lat. Reg."), "sum": True, "pctbase": "reg_total",
                     "tooltip": tr("Hispanic registered voter population")},
    "reg_black": {"caption": tr("Black Reg."), "sum": True, "pctbase": "reg_total",
                  "tooltip": tr("Black registered voter population")},
    "reg_asian": {"caption": tr("Asian Reg."), "sum": True, "pctbase": "reg_total",
                  "tooltip": tr("Asian registered voter population")},
    "reg_mena": {"caption": tr("MENA Reg."), "sum": True, "pctbase": "reg_total",
                 "tooltip": tr("Middle-eastern or North African registered voter population")},
    "reg_aiakn": {"caption": tr("Native Reg."), "sum": True, "pctbase": "reg_total",
                  "tooltip": tr("American Indian or Alaska Native registered voter population")},
    "reg_race_unknown": {"caption": tr("Unk. Race Reg."), "sum": True, "pctbase": "reg_total",
                         "tooltip": tr("Registered voter population whose race is unknown")},
}

all_fields: dict[str, FieldDict] = pop_fields | pop_combination_fields | vap_fields | vap_combination_fields | cvap_fields | gq_fields | vr_fields
